config/routes.rb
Rails.application.routes.draw do
  
  root   'questions#index'
  get    'search', to: 'questions#search'

  resources :questions do

    resources :answers, except: [:index, :show, :new] do
      resources :comments, module: :answers, except: [:index, :show]
      resources :votes,    module: :answers, only: [:create, :destroy]
    end

    resources :comments, module: :questions, except: [:index, :show]
    resources :votes,    module: :questions, only: [:create, :destroy]
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many   :answers, dependent: :destroy
  has_many   :comments, as: :commentable, dependent: :destroy
  has_many   :votes,    as: :votable, dependent: :destroy

  validates :title, presence: true

  validates :body, presence: true

  

  def voted_by?(user)
    votes.exists?(user: user)
  end
end

app/controllers/questions/comments_controller.rb
class Questions::CommentsController < CommentsController
  before_action :set_commentable

  def create
    super
    respond_to do |format|
      format.html { redirect_to @commentable }
      format.js
    end
  end

  def destroy
    @comment = @commentable.comments.find_by(commentable_id: params[:question_id],
                                             id: params[:id])
    if @comment.destroy
      flash[:success] = 'El comentario ha sido eliminado con éxito.'
    end
    redirect_to @commentable
  end

  private
    def set_commentable
      @commentable = Question.find(params[:question_id])
    end
end

app/controllers/questions/votes_controller.rb
class Questions::VotesController < VotesController
  before_action :set_votable

  def create
    super
    redirect_to @votable
  end

  def destroy
    super
    redirect_to @votable
  end

  private

    def set_votable
      @votable = Question.find(params[:question_id])
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]

  def index
    @questions = Question.includes(:votes, :answers)
  end

  def show
    @answer  = Answer.new
    @answers = @question.answers.order_by_oldest.limit(10)
  end

  def search
    search_words = params[:q].downcase
    @questions = Question.includes(:votes, :answers)
                         .where("lower(title) LIKE ? OR lower(body) LIKE ?",
                                "%#{search_words}%",
                                "%#{search_words}%")
                         
    render :index
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      flash[:success] = 'La pregunta ha sido creada con éxito.'
      redirect_to questions_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @question.update(question_params)
      flash[:success] = 'La pregunta ha sido actualizada con éxito.'
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    flash[:success] = 'La pregunta ha sido eliminada con éxito.'
    redirect_to questions_path
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question)
            .permit(:title, :body)
            .merge(user: current_user)
    end

end

app/helpers/questions/comments_helper.rb
module Questions::CommentsHelper
end

app/helpers/questions/votes_helper.rb
module Questions::VotesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div >
      <h2><%= title %></h2>
    </div>
    <div>
      <%= form_with model: question, local: true do |f| %>
        <%= render 'shared/error_messages', model: question %>

        <div >
          <%= f.label :title, "Titulo:" %>
          <%= f.text_field :title, class: "form-control", autofocus: true %>
        </div>

        <div>
          <%= f.label :body, "Descripción:" %>
          <%= f.text_area :body, rows: 10, class: "form-control" %>
        </div>

        <div >
          <%= link_to "Cancelar", questions_path, class: "btn btn-default" %>
          <%= f.submit action, class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/edit.html.erb
<%= render 'form', question: @question, title: "Editar Pregunta", action: "Guardar" %>

app/views/questions/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>Preguntas</h1>
      <% if signed_in? %>
      <div class="text-right">
        <%= link_to "Publicar Pregunta", new_question_path, class: "btn btn-primary" %>
      </div>
      <% end %>
      <table class="table">
        <tr>
          <th>Votos</th>
          <th>respuestas</th>
          <th>Nombre</th>
          <th>Descripción</th>
        </tr>
        <% @questions.reverse_each do |question| %>

          <tr>
          <td class="text-center"><%= question.votes.size%></td>
          <td class="text-center"><%= question.answers.size %></td>
          <td><%= link_to question.title, question%></td>
          <td><%= truncate(strip_tags(markdown(question.body)), length: 100, escape: false) %> 
          <div class="alert alert-warning">
            Publicado por <%= question.user.email %> el <%= (question.created_at.strftime("%d de %b del %Y a las %H:%M")) %>.
          </div></td>   
          </tr>         
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<%= render 'form', question: @question, title: "Publicar Pregunta", action: "Preguntar" %>

app/views/questions/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12" >
      <div class="jumbotron">
        <h1><%= @question.title %></h1>
        <p><%= markdown @question.body %></p>
        <div>
         <%= render 'votes/votes', votable: @question, c_url_path: question_votes_path(@question),  d_url_path: question_vote_path(@question) %>
        </div>
        <div class="alert alert-warning">
          Publicado por <%= @question.user.email %> el <%= (@question.created_at.strftime("%d de %b del %Y a las %H:%M")) %>.
        </div>
      </div>
      <%= render 'answers/form', question: @question, answer: @answer, action: "Publica tu respuesta" %>
    </div>
    <div class="col-sm-12">
      <h3>Comentarios Pregunta</h3>
      <%= render @question.comments %>
    </div>
    <div class="col-sm-12">
      <% if signed_in? %>
          <h2>Añade un comentario</h2>
            <div>
             <%= render 'comments/form', commentable: @question, url_path: question_comments_path(@question) %>
      <% end %>
    </div>
  </div>
</div>             
    <div>
      <div>
        <h2><%= pluralize(@question.answers.count, 'Respuesta', 'Respuestas') %>:</h2>
      </div>

      <% if @question.answers.count > 0 %>
        <%= render @answers %>
      <% else %>
        <%= render 'answers/no_answers' %>
      <% end %>
    </div>
  </div>
</div>