config/routes.rb
Rails.application.routes.draw do
  
  root   'questions#index'
  get    'search', to: 'questions#search'

  resources :questions do

    resources :answers, except: [:index, :show, :new] do
      resources :comments, module: :answers, except: [:index, :show]
      resources :votes,    module: :answers, only: [:create, :destroy]
    end

    resources :comments, module: :questions, except: [:index, :show]
    resources :votes,    module: :questions, only: [:create, :destroy]
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  has_many   :comments, as: :commentable, dependent: :destroy
  has_many   :votes,    as: :votable, dependent: :destroy

  validates :body, presence: true

  scope :order_by_newest, -> { order("id desc") }
  scope :order_by_oldest, -> { order("id asc") }

  def voted_by?(user)
    votes.exists?(user: user)
  end
end

app/controllers/answers/comments_controller.rb
class Answers::CommentsController < CommentsController
  before_action :set_commentable

  def create
    super
    respond_to do |format|
      format.html { redirect_to url_for(@commentable.question) }
      format.js
    end
  end

  def destroy
    @comment = @commentable.comments.find_by(commentable_id: params[:answer_id],
                                             id: params[:id])
    if @comment.destroy
      flash[:success] = 'El comentario ha sido eliminado con éxito.'
    end
    redirect_to url_for(@commentable.question)
  end

  private
    def set_commentable
      @commentable = Answer.find(params[:answer_id])
    end
end

app/controllers/answers/votes_controller.rb
class Answers::VotesController < VotesController
  before_action :set_votable

  def create
    super
    redirect_to url_for(@votable.question)
  end

  def destroy
    super
    redirect_to url_for(@votable.question)
  end

  private

    def set_votable
      @votable = Answer.find(params[:answer_id])
    end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]

  def create
    @answer = Answer.new(answer_params)
    if @answer.save
      flash[:success] = 'La respuesta ha sido registrada con éxito.'
    else
      flash[:danger] = 'La respuesta no puede estar en blanco.'
    end
    redirect_to question_path(params[:question_id])
  end

  def edit
  end

  def update
    if @answer.update(answer_params)
      flash[:success] = 'La respuesta ha sido actualizada con éxito.'
    end
    redirect_to question_path(params[:question_id])
  end

  def destroy
    if @answer.destroy
      flash[:success] = 'La respuesta ha sido eliminada con éxito.'
    end
    redirect_to question_path(params[:question_id])
  end

  private
    def set_answer
      @answer = Answer.find_by(question_id: params[:question_id], id: params[:id])
    end

    def answer_params
      params.require(:answer)
        .permit(:body)
        .merge(user_id: current_user.id, question_id: params[:question_id])
    end
end

app/helpers/answers/comments_helper.rb
module Answers::CommentsHelper
end

app/helpers/answers/votes_helper.rb
module Answers::VotesHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12" >
      <div class="jumbotron">
        <p>
          <%= markdown answer.body %>
        </p>
            <%= render 'votes/votes', votable: answer,
                                      c_url_path: question_answer_votes_path(answer.question, answer),
                                      d_url_path: question_answer_vote_path(answer.question, answer) %>
          <div class="alert alert-warning"> 
            Respuesta por <%= answer.user.email %> el <%= (answer.created_at.strftime("%d de %b del %Y a las %H:%M")) %>.</div>            </div>
      </div>          
      <div>
        <%= render answer.comments %>
      </div>
      <% if signed_in? %>
        <div>
           <h2>Añade un comentario a la respuesta</h2>
        </div>
        <div >
           <%= render 'comments/form', commentable: answer, url_path: question_answer_comments_path(answer.question, answer) %>
        </div>
      <% end %>
      <br>
  </div>
</div>

app/views/answers/_form.html.erb
<% if signed_in? %>
  <h2 class="space">Tu respuesta:</h2>

  <%= form_with model: answer, url: question_answers_path(question), local: true do |f| %>
    <%= render 'shared/error_messages', model: answer %>

    <div class="form-group">
      <%= f.text_area :body, rows: 5, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit action, class: "btn btn-primary" %>
    </div>
  <% end %>
<% end %>

app/views/answers/_no_answers.html.erb
<div >
  <h3>¡Sé el primero en responder!</h3>
</div>

app/views/answers/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="question__header">
      <h2>Actualizar Respuesta</h2>
    </div>
    <div class="question__form">
      <%= form_with model: @answer, url: question_answer_path(@answer.question, @answer), local: true do |f| %>
        <%= render 'shared/error_messages', model: @answer %>
        <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body, rows: 10, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= link_to "Cancelar", question_path(@answer.question.id), class: "btn btn-default" %>
          <%= f.submit "Actualizar", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>